spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_admin_facade
  application:
    name: qipai_admin_facade
    
server:
  port: 99
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/