spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_admin_facade
     
  cloud:
    stream:
      kafka: 
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          gameServerManager:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          signInPrize: 
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberClubCard: 
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        members:
          destination: members
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberGolds:
          destination: memberGolds
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberScores:
          destination: memberScores
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberClubCards:
          destination: memberClubCards
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberOrders:
          destination: memberOrders
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberLoginRecord:
          destination: memberLoginRecord
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        notice:
          destination: notice
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        membershiprights:
          destination: membershiprights
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        grade:
          destination: grade
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        mail:
          destination: mail
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameDataReport:
          destination: gameDataReport
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameServer:
          destination: gameServer
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agents:
          destination: agents
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentApplyRecords:
          destination: agentApplyRecords
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentScores:
          destination: agentScores
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentRewards:
          destination: agentRewards
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentClubCards:
          destination: agentClubCards
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentOrders:
          destination: agentOrders
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentInvitationRecords:
          destination: agentInvitationRecords
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        activity:
          destination: activity
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        tasks:
          destination: tasks
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameServerManager:
          destination: gameServer
          contentType: application/json
          producer:
            partitionCount: 1
        signInPrize:
          destination: signInPrize
          contentType: application/json
          producer:
            partitionCount: 1
        signInPrizeLog:
          destination: signInPrizeLog
          contentType: application/json
          producer:
            partitionCount: 1
        memberClubCard: 
          destination: memberClubCard
          contentType: application/json
          producer:
            partitionCount: 1
        agentImage:
          destination: agentImage
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberLoginLimitRecord:
          destination: memberLoginLimitRecord
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentType:
          destination: agentType
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentRewardOrder:
          destination: agentRewardOrder
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        dianpaoMajiangResult:
          destination: dianpaoMajiangResult
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        ruianMajiangResult:
          destination: ruianMajiangResult
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        fangpaoMajiangResult:
          destination: fangpaoMajiangResult
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouMajiangResult:
          destination: wenzhouMajiangResult
          group: qipai-admin-facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
  application:
    name: qipai-admin-facade
server:
  port: 99
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  #instance:
    #prefer-ip-address: true
    #instance-id: http://172.16.21.51:99