spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_admin_facade
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
      bindings:
        members:
          destination: members
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberGolds:
          destination: memberGolds
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberScores:
          destination: memberScores
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        orders:
          destination: orders
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        game:
          destination: notice
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        membershiprights:
          destination: membershiprights
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        grade:
          destination: grade
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        mail:
          destination: mail
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameServer:
          destination: gameServer
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agents:
          destination: agents
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentApplyRecords:
          destination: agentApplyRecords
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentScores:
          destination: agentScores
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        agentClubCards:
          destination: agentClubCards
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
  application:
    name: qipai-admin-facade
server:
  port: 99
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/