spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_admin_facade
      
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          members:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384

      bindings:
        members:
          destination: members
          group: qipai_admin_facade
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
          producer:
            partitionCount: 1
            
  application:
    name: qipai_admin_facade
    
server:
  port: 99
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/